//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_FINAL_FMGordillo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FacturaDetalle
    {
        [Display(Name = "ID Detalle")]
        public int iddetalle { get; set; }
        [Display(Name = "ID Factura")]
        public int idfactura { get; set; }
        [Display(Name = "ID Articulo")]
        public int idarticulo { get; set; }
        [Display(Name = "Precio *")]
        public decimal precio { get; set; }
        [Display(Name = "Cantidad")]
        public int cantidad { get; set; }
        [Display(Name = "Total *")]
        public decimal total { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
